/*
 * Widget Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace WebApi.Models
{ 
        /// <summary>
        /// Gets or Sets APILibrary.Color
        /// </summary>
        public enum APILibraryColor
        {
            
            /// <summary>
            /// Enum RedEnum for Red
            /// </summary>
            [EnumMember(Value = "Red")]
            RedEnum = 1,
            
            /// <summary>
            /// Enum YellowEnum for Yellow
            /// </summary>
            [EnumMember(Value = "Yellow")]
            YellowEnum = 2,
            
            /// <summary>
            /// Enum PurpleEnum for Purple
            /// </summary>
            [EnumMember(Value = "Purple")]
            PurpleEnum = 3,
            
            /// <summary>
            /// Enum GreenEnum for Green
            /// </summary>
            [EnumMember(Value = "Green")]
            GreenEnum = 4,
            
            /// <summary>
            /// Enum OrangeEnum for Orange
            /// </summary>
            [EnumMember(Value = "Orange")]
            OrangeEnum = 5,
            
            /// <summary>
            /// Enum BlueEnum for Blue
            /// </summary>
            [EnumMember(Value = "Blue")]
            BlueEnum = 6
        }}