/*
 * Widget Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace WebApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GadgetsInterfaceGetGadgets200Response : IEquatable<GadgetsInterfaceGetGadgets200Response>
    {
        private JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            WriteIndented = true
        };

        /// <summary>
        /// List of elements
        /// </summary>
        /// <value>List of elements</value>
        [Required]
        [DataMember(Name="value", EmitDefaultValue=false)]
        public List<Gadget> Value { get; set; }

        /// <summary>
        /// A link to the next page of results if present.
        /// </summary>
        /// <value>A link to the next page of results if present.</value>
        [DataMember(Name="nextLink", EmitDefaultValue=false)]
        public string NextLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GadgetsInterfaceGetGadgets200Response {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  NextLink: ").Append(NextLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, _jsonSerializerOptions);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GadgetsInterfaceGetGadgets200Response)obj);
        }

        /// <summary>
        /// Returns true if GadgetsInterfaceGetGadgets200Response instances are equal
        /// </summary>
        /// <param name="other">Instance of GadgetsInterfaceGetGadgets200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GadgetsInterfaceGetGadgets200Response other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Value == other.Value ||
                    Value != null &&
                    other.Value != null &&
                    Value.SequenceEqual(other.Value)
                ) && 
                (
                    NextLink == other.NextLink ||
                    NextLink != null &&
                    NextLink.Equals(other.NextLink)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (NextLink != null)
                    hashCode = hashCode * 59 + NextLink.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GadgetsInterfaceGetGadgets200Response left, GadgetsInterfaceGetGadgets200Response right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GadgetsInterfaceGetGadgets200Response left, GadgetsInterfaceGetGadgets200Response right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}